# Generated by Django 3.1.4 on 2020-12-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch', models.CharField(max_length=255)),
                ('load_num', models.CharField(max_length=255)),
                ('pickup_num', models.CharField(max_length=255)),
                ('driver', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(max_length=255)),
            ],
        ),
    ]
