# Generated by Django 3.1.4 on 2020-12-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20201223_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='broker',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='board',
            name='delivery',
            field=models.CharField(default='', max_length=2080),
        ),
        migrations.AlterField(
            model_name='board',
            name='dispatch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='board',
            name='driver',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='board',
            name='load_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='board',
            name='mile',
            field=models.CharField(default='', max_length=2080),
        ),
        migrations.AlterField(
            model_name='board',
            name='origin',
            field=models.CharField(default='', max_length=2080),
        ),
        migrations.AlterField(
            model_name='board',
            name='phone_number',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='board',
            name='pickup_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='board',
            name='rate',
            field=models.CharField(default='', max_length=2080),
        ),
    ]
