# Generated by Django 3.1.4 on 2020-12-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_customer_order_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(default='', max_length=300)),
                ('phone_number', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='', max_length=500)),
                ('first_note', models.CharField(default='', max_length=500)),
                ('second_note', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Board',
            new_name='COVERED_LOAD',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
